### ISSUE TITLE
Adverbds

### ISSUE THREAD

**Issue by rdm** [cratelyn/j#2]
Currently, the readme states

"we won't comprehensively explain adverbs here. in short, `+ /` applies the dyadic `+` operator "over" its argument(s)."

But I think it would be easier to understand: ..., `+ /` applies the dyadic `+` operator _"between"_ items of its argument, like a fold.

There's a bit more detail to fully understand what's going on with  `/` (empty case, non-associative examples and evaluation order, non-commutative examples and argument order, language parsing mechanisms and generally speaking, how they implement these concepts, and K's left argument to `+/`). But, for a summary statement, I think emphasizing that `+/1 2 3 4` is equivalent to `1+2+3+4` is critical for reader comprehension.

**Comment by cratelyn** [comment]
hi @rdm! thank you for opening an issue to point this out. i agree that this will help clarify the mechanics of the monadic `/` "_insert_" adverb.

this project is still a work in progress, but i will make a point of adding this emphasis in a future edit.

**Comment by cratelyn** [comment]
the readme has since been updated. i'm going to close this now. thank you for reading!
